version: '3'

services:
    # MongoDB Service
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
            - ./database:/data/import # Gắn thư mục chứa file JSON từ máy cục bộ
        environment:
            MONGO_INITDB_DATABASE: Blog-Page

    # Express Backend Service
    express:
        build: ./backend
        container_name: express
        ports:
            - '5050:5050'
        volumes:
            - ./backend:/app
        depends_on:
            - mongodb
        environment:
            - SERVER_PORT=5050
            - MONGODB_URI=mongodb://mongodb:27017/Blog-Page
            - SECRET_KEY_ACCESS_TOKEN=secret-key-access-token
            - SECRET_KEY_REFRESH_TOKEN=secret-key-refresh-token
            - CLIENT_URL=http://localhost:3000
            - SERVER_URL=http://localhost:5050/api

    # React Frontend Service
    react:
        build: ./frontend
        container_name: react
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
        depends_on:
            - express
        environment:
            - REACT_APP_API_URL=http://localhost:5050/api
