version: '3'

services:
    # MongoDB Service
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
            - ./database:/data/import # Volume chứa file JSON

    # Express Backend Service
    express:
        build: ./backend
        container_name: express
        ports:
            - '5050:5050'
        volumes:
            - ./backend:/app
        depends_on:
            - mongodb
        environment:
            - MONGO_URI=mongodb://mongodb:27017/Blog-Page
            - CLIENT_URL=http://localhost:3000
            - SERVER_PORT=5050

    # React Frontend Service
    react:
        build: ./frontend
        container_name: react
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
        depends_on:
            - express
